services:
  - type: web
    name: meditrack-db
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: BUN_INSTALL
        value: "false"
